# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    
  
  todo:
    container_name: todo_service
    build: .
    depends_on:
      - mongo
    ports:
      - 4000:4000
    environment:
      PORT: :4000
      DB_NAME: mymongo
      TODO_COLLECTION: todo
      JWT_SECRET_KEY: not-secret-key
      ISSUER: auth-svc
      EXPIRATION_HOURS: 1
      DB_URL: mongodb://mongo:27017/mymongo
      CLIENT_PORT: :4000
      